{
 "title": "Traffic Analysis",
 "description": "Traffic Analysis",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Accepted",
   "type": "gauge",
   "description": "Number of connections accepted",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| filter action = \"ACCEPT OK\"\n| stats count()",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "gauge",
   "description": "Number of connections rejected",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| filter action = \"REJECT OK\"\n| stats count()",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total Accepted Since $${__from:date:MMM-DD hh.mma}",
   "type": "gauge",
   "description": "Total number of connections accepted since $${__from:date:MMM-DD hh.mma}",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| filter action = \"ACCEPT OK\"\n| stats count()",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total Rejected Since $${__from:date:MMM-DD hh.mma}",
   "type": "gauge",
   "description": "Total number of connections that were rejected since $${__from:date:MMM-DD hh.mma}",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| filter action = \"REJECT OK\"\n| stats count()",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Local Targets",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| display dstaddr\n| dedup dstaddr",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "All Traffic Sources",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| stats count() as count by srcaddr\n| sort by count desc",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "srcaddr" ]
    }
   ]
  },
  {
   "title": "Traffic Sources Blocked",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| filter action = 'REJECT OK'\n| stats count() as count by srcaddr\n| sort by count desc",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "srcaddr" ]
    }
   ]
  },
  {
   "title": "Traffic Sources Accepted",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| filter action = 'ACCEPT OK'\n| stats count() as count by srcaddr\n| sort by count desc",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "srcaddr" ]
    }
   ]
  },
  {
   "title": "Summary Of Port Numbers Queried",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| stats count() as count by dstport\n| sort by count desc\n| display dstport, count",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "dstport" ]
    }
   ]
  },
  {
   "title": "Raw Traffic Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "expression": "fields @timestamp\n| parse @message '* * * * * * * * * * * * *' as version, account_id, interface_id, srcaddr, dstaddr, srcport, dstport, proto, packets, bytes, start_time, end_time, action\n| filter dstaddr like /10.0.2/\n| sort @timestamp desc",
     "logGroups": [
      {
       "accountId": "919160726272",
       "arn": "arn:aws:logs:ap-southeast-2:919160726272:log-group:/aws/vpc/flowlogs:*",
       "name": "/aws/vpc/flowlogs"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}